### ISSUE TITLE
🐛 Bug Report: OrderAsc throws Server Error

### ISSUE THREAD

**Issue by NickHatBoecker** [appwrite/sdk-for-web#101]
### 👟 Reproduction steps

In my app I have a list of database entries. With sdk-for-web@13.0.0 the following query works without errors. But with sdk-for-web@15.0.0 an errors occurs.

```js
import { Databases, Query } from 'appwrite'


const databases = new Databases(...)

const { documents } = await databases.listDocuments('myapp', 'mytable', [
    Query.orderAsc('title'),
])
```

Looking at the docs nothing has changed regarding the `Query.orderAsc` function:
https://appwrite.io/docs/products/databases/order#one-column

### 👍 Expected behavior

Should return an array of objects.

### 👎 Actual Behavior

GET /v1/databases/lyricly/collections/lyrics/documents?queries%5B0%5D=%7B%22method%22%3A%22orderAsc%22%2C%22attribute%22%3A%22songtitle%22%7D 500 (Internal Server Error)

client.ts:440 Uncaught (in promise) AppwriteException: Server Error
    at Client.<anonymous> (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=b1d84f26:419:17)
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:5173/node_modules/.vite/deps/appwrite.js?v=b1d84f26:13:24)

### 🎲 Appwrite version

Version 1.4.9

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@NickHatBoecker, thanks for creating this issue! 🙏🏼 

This is expected because Version 15 of the SDK is meant for Appwrite 1.5. See https://github.com/appwrite/sdk-for-web/blob/15.0.0/README.md?plain=1#L9
