### ISSUE TITLE
React Native / Expo support

### ISSUE THREAD

**Issue by brunoprietog** [appwrite/sdk-for-web#20]
### 🔖 Feature description

Hello!
Can this sdk be used with React Native? I was thinking that things like authentication with oauth providers would not work.
Thanks!

### 🎤 Pitch

Perhaps some alternative methods could be implemented for executions in these environments.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by rohankm** [comment]
As react native does not have window.localstorage, implementing the same with 
AsyncStorage from '@react-native-async-storage/async-storage'; would be more sense.

i was checking the docs of supabase. This is how they did it and I guess the appwrite SDK developers can get some inspiration and implement something this way.

```
import AsyncStorage from '@react-native-async-storage/async-storage';
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = YOUR_REACT_NATIVE_SUPABASE_URL
const supabaseAnonKey = YOUR_REACT_NATIVE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  localStorage: AsyncStorage as any,
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: false,
});
```

**Comment by stnguyen90** [comment]
Closing in favor of some of the other React Native issues
