### ISSUE TITLE
🐛 Bug Report: getFileView() missing project

### ISSUE THREAD

**Issue by IRules** [appwrite/sdk-for-web#23]
### 👟 Reproduction steps

- try to pull a FileView with the SDK
- print the path to it in the console

### 👍 Expected behavior

path should end with ?project={projectID}

### 👎 Actual Behavior

It end just with ?view, making it impossible for appwrite to know which project the file is pulled from

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Runs on Ubuntu latest, using Cloudflare as my DNS manager and it is proxied via cloudflare. Turning it off has no effect whatsoever.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@IRules Which SDK version you are using?

**Comment by stnguyen90** [comment]
@IRules is this still a problem?

**Comment by IRules** [comment]
No, completely forgot about this ticket, very sorry.
