### ISSUE TITLE
🐛 Bug Report: Realtime/Websocket stuck with previous user after new user has logined

### ISSUE THREAD

**Issue by mcchin** [appwrite/sdk-for-web#24]
#### Config/Setup:
- I am using Appwrite v:0.13.4.304, WebSDK 7.0.0, and node-appwrite 5.0.0
- Database collection is setup as `Document Level` permission
- Documents read permission are assigned appropriately like so, e.g. `user:UserID`
- There is a collection with only couple of documents with read access for `User A`, but **NOT** `User B`

#### To reproduce:

1. Login as `User A` , e.g. `sdk.account.createSession(User A email, User A password)`

2. At a React page, using WebSDK to subscribe to a channel like so 
```
  useEffect(() => {
    const unsubscribe = sdk.subscribe(`collections.COLLECTION_ID.documents`,
      res => {
        console.log('realtime response', res)
      }
    )

    return () => {
      unsubscribe()
    }
  }, [])
```

3. Update any of the documents on the said collection from Appwrite Console, and I can noticed data is received, and channel/subscription callback is executed

4. `User A` logout, `unsubscribe()` is fired, and then `User A` is logout like so `sdk.account.deleteSession('current')` / `sdk.account.deleteSession(session_id)`

5. **At the same browser tab**, `User B` login, e.g. `sdk.account.createSession(User B email, User B password)`, and visit the same page, so step 2 above is executed as well 
**NOTE: Don't refresh browser page, if you have refreshed browser page you can't reproduce the issue**

6. Update any of the documents on the said collection from Appwrite Console, and I can noticed data is received, and channel/subscription callback is executed, **which is not expected behaviour** as only `User A` has read permission, not `User B`

### 👍 Expected behavior

I **should not** receive any channel/subscription callback when I login as `User B`

### 👎 Actual Behavior

I **receive** channel/subscription callback when I login as `User B`, but `User B` doesn't have any read permission on the subscribed data collection (Where the callback response data is for `User A`)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

- Frontend using React 17.x, and WebSDK 7.0.0
- Backend using Node 14.x and Appwrite Node client 5.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@mcchin Thank you for reporting the issue with such details. We will look into the issue and get back to you.

**Comment by TorstenDittmann** [comment]
I'll be closing this in favour of #25
