### ISSUE TITLE
🐛 Bug Report: React Native Realtime

### ISSUE THREAD

**Issue by rohankm** [appwrite/sdk-for-web#28]
### 👟 Reproduction steps

When i Subscribe to any events on react native expo. every 30sec to 1min I get "Realtime got disconnected. Reconnect will be attempted in 1 seconds., undefined" error. 

Steps to reproduce
1. just create a react native expo app
2. subscribe to any collection and check the console logs

### 👍 Expected behavior

connection should be stable

### 👎 Actual Behavior

<img width="773" alt="Screenshot 2022-07-08 at 5 17 45 AM" src="https://user-images.githubusercontent.com/23615452/177889558-b7e5207f-5a99-4818-9139-2fe1f6533b44.png">

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Do you have cloudflare or any reverse proxy in front of appwrite?

**Comment by rohankm** [comment]
> Do you have cloudflare or any reverse proxy in front of appwrite?

im using nginx as reverse proxy

**Comment by stnguyen90** [comment]
> im using nginx as reverse proxy

Your web socket may be timing out. Do you have various timeout directives in place? See [this](https://stackoverflow.com/questions/10550558/nginx-tcp-websockets-timeout-keepalive-config).

On a side note...how did you get realtime working on react native? I thought it didn't work due to window being undefined.

**Comment by rohankm** [comment]
> > im using nginx as reverse proxy
> 
> Your web socket may be timing out. Do you have various timeout directives in place? See [this](https://stackoverflow.com/questions/10550558/nginx-tcp-websockets-timeout-keepalive-config).
> 
> On a side note...how did you get realtime working on react native? I thought it didn't work due to window being undefined.

to be honest I have no idea! somehow the realtime is working and window.localstorage is not causing many issues except console logging periodically

**Comment by rohankm** [comment]
> > im using nginx as reverse proxy
> 
> Your web socket may be timing out. Do you have various timeout directives in place? See [this](https://stackoverflow.com/questions/10550558/nginx-tcp-websockets-timeout-keepalive-config).
> 
> On a side note...how did you get realtime working on react native? I thought it didn't work due to window being undefined.

i added 
```
proxy_connect_timeout 7d;
proxy_send_timeout 7d;
proxy_read_timeout 7d;
```
to my nginx config file and I see that the bug is gone now. Thanks :)
