### ISSUE TITLE
🐛 Bug Report: Realtime doesn't work on React Native

### ISSUE THREAD

**Issue by rohankm** [appwrite/sdk-for-web#29]
### 👟 Reproduction steps

1. create a react native expo app
2. init the appwrite
3. check the console log

### 👍 Expected behavior

As react native does not have window.localstorage, implementing the same with 
AsyncStorage from '@react-native-async-storage/async-storage'; would be more sense.

i was checking the docs of supabase. This is how they did it 

```
import AsyncStorage from '@react-native-async-storage/async-storage';
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = YOUR_REACT_NATIVE_SUPABASE_URL
const supabaseAnonKey = YOUR_REACT_NATIVE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  localStorage: AsyncStorage as any,
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: false,
});
```
 implementing something like this would be helpful

### 👎 Actual Behavior

<img width="773" alt="Screenshot 2022-07-08 at 5 25 10 AM" src="https://user-images.githubusercontent.com/23615452/177890238-579e2855-d427-424d-afd5-59c83082d30b.png">

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@rohankm could you please clarify that realtime in react native is what doesn't work?

**Comment by solita-jtn** [comment]
@stnguyen90 SDK throws the exception below, when trying to subscribe. This is due to that it uses localStorage which is not available in React Native.

```
TypeError: Cannot read properties of undefined (reading 'getItem')
    at WebSocket.onMessage (/xxx/node_modules/appwrite/dist/cjs/sdk.js:181:81)
```

**Comment by prathamesh3707** [comment]
please assign it to me

**Comment by lohanidamodar** [comment]
@rohankm We now have React Native SDK. Please check it out at https://github.com/appwrite/sdk-for-react-native
