### ISSUE TITLE
🐛 Bug Report: Origin localhost not allowed when fetching file

### ISSUE THREAD

**Issue by lkoehl** [appwrite/sdk-for-web#30]
### 👟 Reproduction steps

Running a local instance of appwrite, use Safari as a browser and fetching data from a link returned by `getFileView`

```
const url = storage.getFileView(BUCKET_ID, fileId);
axios
  .get(url.href)
  .then((response) => console.log(response))
  .catch((error) => console.log(error));
```

### 👍 Expected behavior

Returns the data from the file.

### 👎 Actual Behavior

```
[Error] XMLHttpRequest cannot load http://localhost/v1/storage/buckets/62e3ed0fc097798c4bfe/files/62e3ed7e4eafee1a50d1/view?project=625ec35b68a2dcb2d0fd due to access control checks.
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. Status code: 200 (view, line 0)
```

### 🎲 Appwrite version

Version 0.9.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@lkoehl, thanks for raising this issue! 🙏 I tried to reproduce your issue, but I was able to successfully fetch a markdown file and get the text. Would you please make sure your project ID is correct and use https for your endpoint?

**Comment by lkoehl** [comment]
@stnguyen90 thanks. It's works with Safari when setting the endpoint to `https://localhost/v1`. Maybe the README needs an update?
  
https://github.com/appwrite/sdk-for-web/blob/cfc9baa0d265d7ce8f53ca8b10ee870f169f8add/README.md?plain=1#L47-L58

**Comment by stnguyen90** [comment]
@gewenyu99, thoughts on making all of our examples use HTTPS since sometimes there's weird behavior when using HTTP (due to how browsers handle cookies and/or redirects)?

**Comment by stnguyen90** [comment]
@gewenyu99, we seem to be inconsistent. Most are HTTPS except:

1. [swift-client](https://github.com/appwrite/appwrite/blob/c92c2d7b75819b6727b6d6bbb16a4201aa778594/docs/sdks/swift-client/GETTING_STARTED.md?plain=1#L63)
2. [dotnet](https://github.com/appwrite/appwrite/blob/c92c2d7b75819b6727b6d6bbb16a4201aa778594/docs/sdks/dotnet/GETTING_STARTED.md?plain=1#L14)
3. [web](https://github.com/appwrite/appwrite/blob/master/docs/sdks/web/GETTING_STARTED.md?plain=1#L16-L43)
4. [cli](https://github.com/appwrite/appwrite/blob/c92c2d7b75819b6727b6d6bbb16a4201aa778594/docs/sdks/cli/GETTING_STARTED.md?plain=1#L12)

**Comment by gewenyu99** [comment]
I agree. I want to make everything https. This will be true esp. for cloud anyway. I have this written down in the doc contribution guide draft :)

**Comment by TorstenDittmann** [comment]
Localhost and https can create issues on top without any configuration. We should double check that.

Thinking about local dev servers that connect to Appwrite which don't support https oob. Then you run into http -> https conflicts.

This issue only occurs in browsers, that's why non-browser sdks might target https.

**Comment by gewenyu99** [comment]
> Localhost and https can create issues on top without any configuration. We should double check that.
> 
> Thinking about local dev servers that connect to Appwrite which don't support https oob. Then you run into http -> https conflicts.
> 
> This issue only occurs in browsers, that's why non-browser sdks might target https.

I think the real solution will be when we have cloud ;)

Then we can just use the cloud URL as the default example.
