### ISSUE TITLE
🐛 Bug Report: CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by pauli2406** [appwrite/sdk-for-web#34]
### 👟 Reproduction steps

Add the Appwrite web SDK to an angular project.
Run the build command to compile.

`npx nx run oncampus-cms:build --parallel`

Should also occur when execute it with
` ng serve`

### 👍 Expected behavior

No warnings regarding "CommonJS or AMD dependencies can cause optimization bailouts" should appear while compiling the project

### 👎 Actual Behavior

Receiving two warnings with dependencies that are not optimized:
```bash
Warning: /Users/marcelpochert/Programming/Work/on-campus/node_modules/appwrite/dist/esm/sdk.js depends on 'cross-fetch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /Users/marcelpochert/Programming/Work/on-campus/node_modules/appwrite/dist/esm/sdk.js depends on 'isomorphic-form-data'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Using version "appwrite": "^9.0.1"
Angular Version 14.2.0

Withing an nx mono repo

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by aallnneess** [comment]
Hey :-)

Are there any changes here ? I have Appwrite version SDK 13 and still the same behavior.

thanks

**Comment by aallnneess** [comment]
@pauli2406 Hey :-)

Are there any changes here ? I have Appwrite version SDK 13 and still the same behavior.

thanks

**Comment by stnguyen90** [comment]
We've removed node-fetch and isomorphic-form-data in https://github.com/appwrite/sdk-for-web/releases/tag/15.0.0 so this shouldn't be a problem anymore. Feel free to leave a comment if otherwise.
