### ISSUE TITLE
📚 Documentation: links looks wrong at the bottom of Readme file

### ISSUE THREAD

**Issue by sinadarvi** [appwrite/sdk-for-web#44]
### 💭 Description

The **Getting Started** link at the bottom of the readme file (below the [Learn More](https://github.com/appwrite/sdk-for-web#learn-more) section) looks wrong. If you click on it, you will be navigated to getting started with flutter docs. even in the last link, **flutter** have been mentioned in it. "[Appwrite **Flutter** Playground](https://github.com/appwrite/playground-for-flutter)". 

also, the "Code of Conduct" link is broken too. I didn't see such a file nor in this repo or appwrite itself.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sinadarvi thanks for raising this! Looks like this is incorrect:

https://github.com/appwrite/appwrite/blob/8dfdef6006fa5851ffaba0345c33b3c31d6bb3c0/docs/sdks/web/GETTING_STARTED.md?plain=1#L60-L63

**Comment by Atsurak** [comment]
so here are the links for getting started with web [https://appwrite.io/docs/getting-started-for-web](https://appwrite.io/docs/getting-started-for-web) and web playground [https://github.com/appwrite/playground-for-web](https://github.com/appwrite/playground-for-web) should I raise a PR to fix this?

**Comment by Atsurak** [comment]
link to code of conduct is broken in all repos are there any plans to fix this?

**Comment by stnguyen90** [comment]
> link to code of conduct is broken in all repos are there any plans to fix this?

@Atsurak, yes, there's a [PR](https://github.com/appwrite/.github/pull/11) for that pending merge.

**Comment by stnguyen90** [comment]
Fixed by https://github.com/appwrite/appwrite/pull/5360
