### ISSUE TITLE
🐛 Bug Report:  registration using websdk fails with API fetch loading failed

### ISSUE THREAD

**Issue by psschand16** [appwrite/sdk-for-web#49]
### 👟 Reproduction steps

Using Web SDK

Interacting with self hosted appwrite endpoint hosted on a subdomain endpoint.

The SDK fails at times mysteriously , at times it works

can you please let me know if I am missing anything.

<img width="815" alt="appwrite error Screenshot 2023-01-31 090248" src="https://user-images.githubusercontent.com/61744673/215745757-43a07f4f-115b-4449-afa6-de8585265297.png">

### 👍 Expected behavior

fetch should be successful

### 👎 Actual Behavior

api fetch is failing for login/Register

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

html page on Live server, acessed via chrome browser

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@psschand16, thanks for creating this issue! 🙏🏼 I can see the 401 response status, but would you please share the HTTP response body for the create email session API call?

**Comment by stnguyen90** [comment]
@psschand16 thanks for all the info! 🙏🏼 I think this is just a problem with the playground for web: https://github.com/appwrite/playground-for-web/issues/80
