### ISSUE TITLE
🐛 Bug Report:  Module appwrite has no member Appwrite

### ISSUE THREAD

**Issue by sannanansari** [appwrite/sdk-for-web#50]
While installing the appwrite in angular, I am getting following error
> `Module '"appwrite"' has no exported member 'Appwrite'.ts(2305)`

**Comment by sannanansari** [comment]
can work on this issue?

**Comment by stnguyen90** [comment]
@sannanansari, thanks for creating this issue! 🙏🏼 

I don't think you should be importing `Appwrite`. Where do you see that you need to import `Appwrite`?

**Comment by sannanansari** [comment]
@stnguyen90 Thanks. currently for importing appwrite we use
 `import { Client } from 'Appwite' `

 with respect to angular @stnguyen90.

It better we use **Appwrite** inplace of **Client**

> I don't think you should be importing Appwrite. Where do you see that you need to import Appwrite?

Here:- https://github.com/appwrite/demo-todo-with-angular/blob/main/src/app/helpers/api.ts

**Comment by stnguyen90** [comment]
@sannanansari, that code sample you linked uses an old SDK version, which exports `Appwrite`. If you want, you can use an alias like:

```javascript
import { Client as Appwrite } from 'appwrite';
```

**Comment by stnguyen90** [comment]
@sannanansari, is there anything else or can this be closed?
