### ISSUE TITLE
Remove cross-fetch and isomorphic-form-data

### ISSUE THREAD

**Issue by jimmywarting** [appwrite/sdk-for-web#53]
https://github.com/appwrite/sdk-for-web/blob/7b37a2bec1dbe47b55e2c962996046f56b763192/package.json#L34-L37

formdata + fetch is built-in to all evergreen env. (NodeJS v18+)
if it isn't just let the developer who depend on this package bring them in themself if they need to.

**Comment by SayyamJain101** [comment]
Can you assign me this issue @jimmywarting

**Comment by stnguyen90** [comment]
Fixed as part of https://github.com/appwrite/sdk-for-web/releases/tag/15.0.0
