### ISSUE TITLE
🐛 Bug Report: Not able to detect Appwrite Web SDK Types

### ISSUE THREAD

**Issue by nimit2801** [appwrite/sdk-for-web#54]
### 👟 Reproduction steps

Step 1: Initialize a `Vite` Project
```clie
yarn create vite my-vue-app --template vanilla-ts
```

**Root Cause**
Because `"moduleResolution"` is set to `"bundler"` in my `tsconfig.json`

Step 2: Install appwrite 
```cli
yarn add appwrite
```

Step 3: Import App
```ts
import {Client} from "appwrite"
```

### 👍 Expected behavior

It should not throw an error!

### 👎 Actual Behavior

It throws an error
```error
 Could not find a declaration file for module 'appwrite'. 'c:/Users/ASUS/OneDrive/Desktop/my-vue-app/node_modules/appwrite/dist/esm/sdk.js' implicitly has an 'any' type.
  There are types at 'c:/Users/ASUS/OneDrive/Desktop/my-vue-app/node_modules/appwrite/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'appwrite' library may need to update its package.json or typings.
```
![image](https://user-images.githubusercontent.com/53462249/236686193-327190ea-96ff-4e03-9ea0-996995d7824e.png)

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Nope!

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nimit2801 thanks for raising this issue!

After googling a bit it seems like this might be a newer typescript config and we can get it to work if we update a few things in the sdk. 

Some additional reference:

* https://github.com/microsoft/TypeScript/issues/52363
* https://github.com/gxmari007/vite-plugin-eslint/pull/60
* https://github.com/nolimits4web/swiper/issues/6508

**Comment by nimit2801** [comment]
### Possible solution which worked for me

My `tsconfig.json` file has `"moduleResolution": "bundler"` and if I set it to `"moduleResolution": "node"` it works for me!

**Comment by stnguyen90** [comment]
We should be able to fix the problem If we update the exports in our package.json to:

```json
  "exports": {
    ".": {
      "import": "./dist/esm/sdk.js",
      "require": "./dist/cjs/sdk.js",
      "types": "./types/index.d.ts"
    },
    "./package.json": "./package.json"
  },
```

**Comment by nimit2801** [comment]
Thought for food
https://github.com/gxmari007/vite-plugin-eslint/pull/60
this solves

**Comment by nimit2801** [comment]
> We should be able to fix the problem If we update the exports in our package.json to:
> 
> ```json
>   "exports": {
>     ".": {
>       "import": "./dist/esm/sdk.js",
>       "require": "./dist/cjs/sdk.js",
>       "types": "./types/index.d.ts"
>     },
>     "./package.json": "./package.json"
>   },
> ```

Yup, exactly. Can I make a PR?

**Comment by subhojit-ghosh** [comment]
> ### Possible solution which worked for me
> My `tsconfig.json` file has `"moduleResolution": "bundler"` and if I set it to `"moduleResolution": "node"` it works for me!

this is not working when I am trying to build the project. I am using Vitejs and react

**Comment by nimit2801** [comment]
> > ### Possible solution which worked for me
> > My `tsconfig.json` file has `"moduleResolution": "bundler"` and if I set it to `"moduleResolution": "node"` it works for me!
> 
> this is not working when I am trying to build the project. I am using Vitejs and react <img alt="image" width="1112" src="https://user-images.githubusercontent.com/45323851/241394921-435c5368-c7bc-4b5a-8253-1ff0cc0c25b6.png">

Did you make the necessary changes? I suggested in the above solution.



> ### Possible solution which worked for me
> 
> My `tsconfig.json` file has `"moduleResolution": "bundler"` and if I set it to `"moduleResolution": "node"` it works for me!

**Comment by colbyfayock** [comment]
still seeing this in a fresh vite project - should this issue still be open?

<img width="1080" alt="image" src="https://github.com/appwrite/sdk-for-web/assets/1045274/2642fd42-1977-4481-b2a2-4958729381ca">

is `"moduleResolution": "node"` the "right" solution? or a workaround? without knowing the total scope of that change, im wondering if it would be appropriate for all apps or if that might cause conflicts in some, but seems like it may be a package issue?

**Comment by stnguyen90** [comment]
@colbyfayock 

> still seeing this in a fresh vite react project - should this issue still be open?

The fix will be in the next release of the SDK.

> is "moduleResolution": "node" the "right" solution? or a workaround? 

Both? The problem was the newer TS config is incompatible with our SDK.
