### ISSUE TITLE
🚀 Feature: List collections

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [appwrite/sdk-for-web#56]
### 🔖 Feature description

I would be nice if the list collections method is implemented in the web-sdk as well.
Currently only the node server SDK includes the listCollections method.

Is there any restriction on why this can't we used on the web-sdk?

### 🎤 Pitch

To be more flexible it would be nice to also have some methods from the node-sdk available in the web-sdk. I could then remove the node-js middleware.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
To ensure the highest level of security, the client SDKs of Appwrite do not include database or collection-related operations. This deliberate design choice prevents the unnecessary exposure of non-relevant collections and databases. By limiting access to only the required data, potential security risks are mitigated, as sensitive information is not exposed to unauthorized parties. This approach prioritizes data privacy and enhances overall application security.

A workaround would be to use Functions in Appwrite to implement this!

**Comment by mariomurrent-softwaresolutions** [comment]
Alright, sounds good.
Well I'll go the other way and build my own middleware including the appwrite server SDK.

Thx for clarification
