### ISSUE TITLE
🐛 Bug Report: Upload Progress not being reported

### ISSUE THREAD

**Issue by mariusbolik** [appwrite/sdk-for-web#58]
### 👟 Reproduction steps

```ts
    try {
      const upload = await storage.createFile('uploads', ID.unique(), file, [Permission.read(Role.any())], (uploadProgress) => {
        console.log('Progress', uploadProgress)
      });

      console.log("Upload completed", upload);
    } catch (error) {
      console.error("Error while uploading file: ", error);
    }
  };
```

### 👍 Expected behavior

The console.log in the callback should be updated, so I can report the upload progress to the user.

### 👎 Actual Behavior

Sadly, the callback isn't emitting any events. The file gets uploaded correctly.

### 🎲 Appwrite version

Cloud Beta

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@mariusbolik thanks for creating this issue! 🙏 How big is the file you're uploading?

**Comment by stnguyen90** [comment]
@mariusbolik would you please provide some more information. FYI, we'll need to close this due to inactivity soon.

**Comment by stnguyen90** [comment]
The progress is only triggered if the file is over 5MB as the progress is updated per 5MB chunk.
