### ISSUE TITLE
🐛 Bug Report: storage.createFile() looses mimeType and stops at 0 bytes when uploading

### ISSUE THREAD

**Issue by trashcoder** [appwrite/sdk-for-web#61]
### 👟 Reproduction steps

When using sdk-for-web for react-native createFile looses the mimetype and stops at 0 bytes when uploading a file

   const blob = new Blob(['Hello World'], {
      type: 'plain/text',
    } as BlobOptions);
    //@ts-ignore
    const file = new File([blob], fileName, {type: blob.type});
    const response = await storage.createFile(BUCKET_ID, ID.unique(), file);

<img width="1191" alt="Bildschirmfoto 2023-07-03 um 23 23 00" src="https://github.com/appwrite/sdk-for-web/assets/2404165/037f6372-7127-4dbb-aa98-36fd6ab5b02a">

The same behaviour is when i upload an image from rn-image-picker.

### 👍 Expected behavior

it should upload a file and keeping the mimetype.

### 👎 Actual Behavior

it stops at 0 bytes and looses the mimeType.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Client Version: 11.0.0
Appwrite Server: 1.3.7
React-Native Version: 0.71.11

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@trashcoder, thanks for creating this issue! 🙏🏼 Unfortunately, createFile doesn't work with react-native. See https://github.com/appwrite/sdk-for-web/issues/27
