### ISSUE TITLE
🚀 Feature: List Teams in Account.get()

### ISSUE THREAD

**Issue by silentmado** [appwrite/sdk-for-web#62]
### 🔖 Feature description

I don't find a way to get the list of teams that the user belongs to, unless using Users.

I need to manage the logged user authorizations in my app, so I think it would be very useful if we can find out which Teams the user is a member of in the Account Object returned by Account.get().

### 🎤 Pitch

It will be very easy to manage authorizations in the application.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by trashcoder** [comment]
Doesn't
`const promise = teams.list();`

work for this?

docs says:
Get a list of all the teams in which the current user is a member. You can use the parameters to filter your results.

**Comment by lohanidamodar** [comment]
@trashcoder you are correct. While using client SDK, `teams.list` returns the teams current user is member of. @silentmado you should make a request, using teams service.
