### ISSUE TITLE
Unable to get the Response Error

### ISSUE THREAD

**Issue by eladcandroid** [appwrite/sdk-for-web#7]
You just reject with the request.responseText, here:
https://github.com/appwrite/sdk-for-js/blob/3f71ea130d6c91ea484f9de821a9ec74345d4160/src/sdk.js#L214

What about the cases when we want to get the error message? For example:
{"message":"Too many requests","code":429,"version":"0.6.2"}

Maybe you should add a case and send request.response when it exists..

**Comment by eldadfux** [comment]
Thanks for the feedback Elad! This definitely make sense.

This is a breaking change so will try to schedule it with version 0.7 of the Appwrite server which should introduce some breaking changes to the SDKs anyway.

**Comment by delaneyj** [comment]
I was search the docs for this exact issue.  :+1:

**Comment by eldadfux** [comment]
New error format for the JS SDK:
![image](https://user-images.githubusercontent.com/1297371/84736989-ad4f1480-afaf-11ea-839d-8b003e2e0648.png)

**Comment by delaneyj** [comment]
Awesome... Is there a way to avoid or turnoff the first 401 logging?

**Comment by eldadfux** [comment]
Only by hiding network errors from your own console. More info on this can be found here: https://stackoverflow.com/questions/41515732/hide-401-console-error-in-chrome-dev-tools-getting-401-on-fetch-call

**Comment by eldadfux** [comment]
Fix has been committed: https://github.com/appwrite/sdk-generator/commit/1f35db85cfb4946c3e1a98499049c0d8a61bb23b

**Comment by naman360** [comment]
Can I work on thiis issue?

**Comment by eldadfux** [comment]
Hey @naman360 this issue has already been fixed. We'll release a new version with the release of Appwrite 0.7

**Comment by eldadfux** [comment]
Fixed on Appwrite Web SDK 2.0
