### ISSUE TITLE
🐛 Bug Report: JSDocstrings for functions not appearing in VSCode Intellisense thingy when using Web SDK

### ISSUE THREAD

**Issue by RyanBaig** [appwrite/sdk-for-web#84]
### 👟 Reproduction steps

1. Open HTML file.
2.  Add Web SDK CDN.
3.  Initialize Appwrite Client using:
```js
const client = new Appwrite.Client()
```
4. Set Projects, Endpoint:
```js
client.setProject("myProject");
client.setEndpoint("https://cloud.appwrite.io/v1")
```
5. Hover over `client.setProject("myProject");` or `client.setEndpoint("https://cloud.appwrite.io/v1")` and see no JSDocstring.

### 👍 Expected behavior

When I hover over the `client.setProject("myProject");` or `client.setEndpoint("https://cloud.appwrite.io/v1")` part, it should show the JSDoc using this Docstring provided in your source code:
```js
/**
     * Set Endpoint
     *
     * Your project endpoint
     *
     * @param {string} endpoint
     *
     * @returns {this}
*/
```
or 
```js
/**
     * Set Project
     *
     * Your project ID
     *
     * @param value string
     *
     * @return {this}
*/
```
 

### 👎 Actual Behavior

They actually don't. I am not sure if this is a problem by the IDE or not.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Vercel for hosting. VSCode 1.70.3 as IDE, Windows 7 for OS, HP Probook 4520s for Machine

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@RyanBaig, thanks for raising this issue! 🙏🏼 Does this work with any other package from CDN? Do you have a code sample of it working with another CDN? I tried with lodash and didn't get any typing info:

<img width="562" alt="image" src="https://github.com/appwrite/sdk-for-web/assets/1477010/97419631-995d-4ffd-82f7-78308ff58de5">

From my experience, your IDE knows about packages when you have a package.json and install the package so it's in your node_modules. When you add a script tag for a package, the IDE has no idea about the types and whatnot about the package.

**Comment by stnguyen90** [comment]
Closing as stale.
