### ISSUE TITLE
🐛 Bug Report: Node dependencies prevent SSR (like Remix) on Cloudflare Pages

### ISSUE THREAD

**Issue by jgentes** [appwrite/sdk-for-web#85]
### 👟 Reproduction steps

Using https://github.com/Meldiron/appwrite-ssr-remix from @Meldiron, replace `@remix-run/node` with `@remix-run/cloudflare`.

The workaround (for Node) is to use `installGlobals` as seen in https://github.com/Meldiron/appwrite-ssr-remix/blob/main/server.ts, however this is not available for Cloudflare as Workers use the V8 runtime.

### 👍 Expected behavior

The client should not use isomorphic libraries, and instead determine which libraries to use based on the platform. <-- guessing here

### 👎 Actual Behavior

Using `import { Client } from 'appwrite'` in a server file will cause `Uncaught ReferenceError: window is not defined` due to the use of `node_modules/isomorphic-form-data/lib/browser.js` which does not work on edge (Workers). Pages is built on Workers, so it prevents deployment.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Update: we have a pending PR with a fix for this here: https://github.com/appwrite/sdk-generator/pull/799

**Comment by stnguyen90** [comment]
https://www.npmjs.com/package/node-appwrite/v/12.1.0-rc.4 is now available.
