### ISSUE TITLE
🐛 Bug Report: cloud.appwrite.io/v1/account/sessions/current 400 (Bad Request)

### ISSUE THREAD

**Issue by jgentes** [appwrite/sdk-for-web#87]
### 👟 Reproduction steps

Issue `await account.updateSession('current')` which sends a request to `https://cloud.appwrite.io/v1/account/sessions/current` and results in `AppwriteException: invalid_request: Missing required parameter: refresh_token`

### 👍 Expected behavior

The docs suggest using the string `current` to refresh the current session, however that appears to be an invalid request: https://appwrite.io/docs/references/cloud/client-web/account

### 👎 Actual Behavior

400 response from the endpoint

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

This is after authenticating with oAuth (Google) - I can issue `account.getSession('current')` and it returns fine. This is being issued from the browser, not Node.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@jgentes, thanks for raising this issue! 🙏🏼 This method is used when a user has an OAuth2 session and they need to refresh the access token from the provider. is that what you're trying to do?

**Comment by jgentes** [comment]
Yes, this is after authenticating with oAuth (Google) - I can issue account.getSession('current') and it returns fine. This is being issued from the browser, not Node.

**Comment by stnguyen90** [comment]
@jgentes, oh wait. you're trying to refresh a google oauth2 session? There's an open issue with google's oauth2 as we aren't getting the refresh token. I would suggest you add a 👍🏼 to https://github.com/appwrite/appwrite/issues/5987. As that's the underlying issue, I'm going to close this as a duplicate.
