### ISSUE TITLE
🐛 Bug Report: Realtime ws unsubscribe does not work as expected

### ISSUE THREAD

**Issue by behics** [appwrite/sdk-for-web#91]
### 👟 Reproduction steps

unsubscribe does not work as expected for the following code block
```ts
  startListener() {
    if (!this.listenerFn) {
      this.listenerFn = this.notification.connect();
    }
  }

  unsubscribeListener() {
    // Stop listening to notifications
    if (this.listenerFn) {
      this.listenerFn();
      console.log('Notification Service stopped');
    }
```

doc [ref](https://appwrite.io/docs/apis/realtime#unsubscribe):
```js
import { Client } from "appwrite";

const client = new Client()
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setProject('<PROJECT_ID>');

const unsubscribe = client.subscribe('files', response => {
    // Callback will be executed on changes for all files.
    console.log(response);
});

// Closes the subscription.
unsubscribe();
```

demo video:

https://github.com/appwrite/sdk-for-web/assets/3280475/825ae55c-05c8-4d75-8f15-35b680926881

### 👍 Expected behavior

it should close the websocket totally. i can see the network tab of inspector

### 👎 Actual Behavior

when i call unsubscribe, it doesnt trigger to and after logout it continues to listen.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

appwrite version 1.4.13
sdk for web "appwrite": "^13.0.0",

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by behics** [comment]
Related with #40

**Comment by stnguyen90** [comment]
@behics, thanks for creating this issue! 🙏🏼 Since we already have https://github.com/appwrite/appwrite/issues/7584. It would be good to just use that 1 issue. Please make sure to add a 👍🏼 to that issue.
